# Generated by Django 6.0.4 on 2026-04-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickettype',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='tickettype',
            name='events_tick_event_i_b78a09_idx',
        ),
        migrations.RemoveIndex(
            model_name='tickettype',
            name='events_tick_sales_s_0983d2_idx',
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_available__lte', models.F('quantity_total'))), name='available_lte_total'),
        ),
    ]
