# Generated by Django 6.0.4 on 2026-04-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_tickettype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='expire_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
